[tool.poetry]
name = "bumblebee"
version = "0.1.0"
description = ""
authors = ["Arun <arunvickram@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0.3"
rq = "^1.16.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
